---
## Re-usable workfloww to commit changes made in pipelines.
#  Usage:
#    In another pipeline, add a step that calls this workflow:
#       - name: Commit changes back to branch
#         uses: ./.github/workflows/commit-changes.yml
#
#  Inputs:
#    commit_message: Commit message to use. If not provided, defaults to "Changes committed from pipeline"

name: Commit Changes

on:
  ## Allows this workflow to be called by other workflows
  workflow_call:
    inputs:
      commit_message:
        required: false
        type: string
        default: "Changes committed from pipeline"

jobs:
  commit-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "${{ inputs.commit_message }}"
          git push origin HEAD:${{ github.event.pull_request.head.ref }}
