---
## Github Action to run tests in nox with uv
name: Run tests with nox
on:
  ## Make this an on-demand Action
  # workflow_dispatch:
  ## Make this callable in other workflows
  workflow_call:
    inputs:
      uv_version:
        required: false
        type: string
        default: "latest"
      commit_title:
        required: false
        type: string
        default: Update packages
      commit_message:
        required: false
        type: string
        default: "chore: bump dependencies using uv"
      commit_body:
        required: false
        type: string
        default: "Automated dependency version bumps via uv"
  ## Execute on PRs to main
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened

jobs:

  run-tests:
    runs-on: ubuntu-latest
    steps:
      ## Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      ## Install uv in pipeline
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "${{ inputs.uv_version || 'latest' }}"

      ## Update packages
      - name: Install project
        run: uv sync --all-extras

      ## Run tests
      - name: Run tests
        run: uv run nox -s tests
