---
###########################################################
# WARNING: This is untested until this comment is removed #
###########################################################

## Publish a package to TestPyPI
name: Publish to TestPyPI

on:
  workflow_dispatch:
    inputs:
      test_pypi_token:
        description: "TestPyPI API token"
        required: true
      commit_message:
        description: "Commit message"
        required: false
        default: "chore: bump version and publish to TestPyPI"

jobs:
  build-and-upload-testpypi:
    runs-on: ubuntu-latest

    steps:
      ## Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      ## Install uv
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      ## Prepare environment
      - name: Install dependencies
        run: uv sync --all-extras

      ## Build the package
      - name: Build the package
        run: uv build

      ## Publish to TestPyPI
      - name: Publish to TestPyPI
        env:
          UV_PUBLISH_TOKEN: ${{ github.event.inputs.test_pypi_token }}
        run: uv publish --publish-url https://test.pypi.org/legacy/
