---
###########################################################
# WARNING: This is untested until this comment is removed #
###########################################################

## Publish a package to PyPI.

name: Publish to PyPI

on:
  ## Uncomment to make this an on-demand workflow
  workflow_dispatch:
    inputs:
      pypi_token:
        description: "PyPI API token"
        required: true
      commit_message:
        description: "Commit message"
        required: false
        default: "chore: publish to PyPI"
  
  ## Uncomment to trigger from other pipelines
  # workflow_call:
  #   inputs:
  #     commit_message:
  #       description: "Commit message"
  #       required: false
  #       default: "chore: publish to PyPI"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      ## Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      ## Install uv
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      ## Prepare environment
      - name: Prepare environment
        run: |
          uv sync --all-extras

      ## Build the package
      - name: Build the package
        run: uv build

      ## Publish to PyPI
      - name: Publish to PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ github.event.inputs.pypi_token }}
        run: uv publish
