###########################################################
# WARNING: This is untested until this comment is removed #
###########################################################

## Lint code with ruff
name: Code Quality Check

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
    paths:
      ## Uncomment path patterns appropriate for your app
      #  to check them with ruff.
      - "src/**"
      # - "sandbox/**"
      # - "scripts/**"
      - "tests/**"
      # - "migrations/**"
      # - "alembic/**"
      # - "packages/**"
      # - "libs/**"
      # - "applications/**"
      ## Any Python file in the root directory (non-recursive)
      - "*.py"
    paths-ignore:
      ## Ignore patterns, don't lint with ruff
      - ".venv/**"
      - ".nox/**"
      - ".ruff/**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      ## Checkout repository
      - uses: actions/checkout@v4

      ## Install Python in container
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      ## Install uv in container
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      ## Setup venv, install dependencies
      - name: Create virtual environment and install dependencies
        run: |
          uv sync
          uv pip install ruff

      ## Check with ruff
      - name: Run Ruff checks & fix errors
        run: |
          ruff check src/
          ruff check sandbox/
          ruff check scripts/
          ruff check tests/
          ruff check migrations/
          ruff check alembic/
          ruff check packages/
          ruff check libs/
          ruff check applications/
          ruff check ./*.py
