###########################################################
# WARNING: This is untested until this comment is removed #
###########################################################

## Lint code with ruff
name: Code Quality Check

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
    ## Run only when changes detected in specified paths
    # paths:
      ## Changes in a src/ directory
      # - "src/**"
      ## Changes in a sandbox/ directory
      ## Any Python file in the root directory (non-recursive)
      # - "./*.py"
    ## Ignore changes in specified paths, don't trigger pipeline
    paths-ignore:
      ## Ignore changes in a tests/ directory
      - "tests/*"
      ## Ignore changes to any Jupyter notebooks
      - "*.ipynb"
      ## Ignore changes in a migrations or alembic directory
      - "migrations/*"
      - "alembic/*"
      ## Ignore changes in a docs/ directory
      - "docs/*"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      ## Checkout repository
      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      ## Install Python in container
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      ## Install uv in container
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      ## Setup venv, install dependencies
      - name: Create virtual environment and install dependencies
        run: |
          uv sync
          uv pip install ruff

      ## Check with ruff
      - name: Run Ruff checks & fix errors
        run: |
          ruff check src/ sandbox/ scripts/ tests/ migrations/ alembic/ packages/ libs/ applications/ ./*.py --fix
